"""Reusable EL4090 occupied-body support-envelope mathematics."""

from .model import (
    EL4090_JOINT_NAMES,
    EL4090_LEG_NAMES,
    LEGACY_HAA_ORDER,
    BatchedUrdfKinematics,
    CapsuleProxy,
    EnvelopeJointRangeExport,
    EnvelopeRangeDiagnostics,
    HaARejectionRanges,
    JointRangeDiagnostics,
    JointRangeExport,
    JointRejectionRanges,
    LegRejectionRanges,
    UrdfJoint,
    add_support_margin,
    append_legacy_envelop2_observation,
    capsule_support,
    contains_points,
    default_el4090_capsules,
    default_el4090_torso_capsules,
    deterministic_joint_samples,
    export_envelope_joint_ranges,
    export_envelope_joint_ranges_at_reference,
    export_sample_bounding_ranges,
    feasible_reference_q,
    foot_positions,
    haa_ranges_from_joint_export,
    haa_rejection_ranges,
    joint_rejection_ranges,
    leg_rejection_ranges,
    legacy_condition_from_support,
    load_urdf_joints,
    point_violations,
    reachable_foot_support,
    support_directions,
)

__version__ = "0.1.0"

__all__ = [
    "EL4090_JOINT_NAMES", "EL4090_LEG_NAMES", "LEGACY_HAA_ORDER",
    "BatchedUrdfKinematics", "CapsuleProxy", "EnvelopeJointRangeExport",
    "EnvelopeRangeDiagnostics", "HaARejectionRanges", "JointRangeDiagnostics",
    "JointRangeExport", "JointRejectionRanges", "LegRejectionRanges", "UrdfJoint",
    "add_support_margin", "append_legacy_envelop2_observation", "capsule_support",
    "contains_points", "default_el4090_capsules", "default_el4090_torso_capsules",
    "deterministic_joint_samples", "export_envelope_joint_ranges",
    "export_envelope_joint_ranges_at_reference", "export_sample_bounding_ranges",
    "feasible_reference_q", "foot_positions", "haa_ranges_from_joint_export",
    "haa_rejection_ranges", "joint_rejection_ranges", "leg_rejection_ranges",
    "legacy_condition_from_support", "load_urdf_joints", "point_violations",
    "reachable_foot_support", "support_directions",
]
